### PR TITLE
 Switched texts "core" -> "ball" for consistancy

### PR DESCRIPTION
**Pull request by jackyedgeworth**
I'll probably made more trash edits later tonight

### CODE REVIEW

**Comment by SunTheCourier** [comment]
resolve conflicts then merge

**Comment by SunTheCourier** [comment]
add commit ['hotfix'](https://github.com/SunTheCourier/Splatoon-2-Meme-ROM-hack/commit/3ba9b08728e45120fc783a134a12eebee1a862cf) and ['fix double space'](https://github.com/SunTheCourier/Splatoon-2-Meme-ROM-hack/commit/b8cda7467d687152e4ea2a183ead7c62132bf4ef)

**Comment by jackyedgeworth** [comment]
fixed

**Comment by SunTheCourier** [comment]
wow just for me???

**Pull request merged**
